# Generated by Django 2.2.6 on 2021-04-03 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
